# compare two mechanism: bread crumb and opportunity.
import re
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter  # useful for `logit` scale
from mininet.log import setLogLevel, output, info
from subprocess import call

def drawGraph(dataPath, dataDir):
    "dataPath: the path stored experimental data"
    "dataDir: the directory specially makeed for emulation protocol"
    dataList = os.listdir("%s/data/%s" % (dataPath, dataDir))
    dataList = readDataFile(dataList)
    sortDataList = sortDataFile(dataList)
    genGraphData(dataPath, dataDir, sortDataList)

def readDataFile(dataFileList):
    "dataFileList: all of files list in dataDir"
    # Delete other files that they are "statResult" from a data file list
    i = 0
    for dataFileName in dataFileList:
        if not ("statResult" in dataFileName):
            dataFileList.pop(i)
        i = i+1
    return dataFileList
def sortDataFile(dataFileList):
    # Sort data file according to file name (the number of nodes) by using bubble algorithm
    i = 0
    while i < len(dataFileList)-1:
        try:
            j = 0
            while j < len(dataFileList)-1-i:
                fileName = dataFileList[j].strip()
                startChar = fileName.index("-") + len("-")
                endChar = fileName.index(".", startChar)
                nodeNumber_j = fileName[startChar : endChar]
                # after j
                fileName=dataFileList[j+1].strip()
                startChar = fileName.index("-") + len("-")
                endChar = fileName.index(".", startChar)
                nodeNumber_j1 = fileName[startChar : endChar]
                if int(nodeNumber_j1.strip()) < int(nodeNumber_j.strip()):
                    tmp = dataFileList[j]
                    dataFileList[j] = dataFileList[j+1]
                    dataFileList[j+1] = tmp
                j = j+1
        except:
            pass
        i = i+1
    return dataFileList
# Calculate graph data from statistic data file
def genGraphData(dataFilePath, dataFileDir, dataFileList):
    graphData_file = open ("%s/data/%s/graphData.dat" % (dataFilePath,dataFileDir), "a")
    for statDataFileName in dataFileList:
        try:
            startChar = statDataFileName.index("-") + len("-")
            endChar = statDataFileName.index(".", startChar)
            nodeNumber = statDataFileName[startChar : endChar]
            statData_file = open ("%s/data/%s/%s" % (dataFilePath, dataFileDir, statDataFileName), "r")
            conNumOutInt = 0
            numOutInt = 0
            aveDelay = 0
            intPacLossRate = 0
            dataPacLossRate = 0
            pacLossRate = 0
            expNumber = 0 # experimental times
            lineField = []
            for line in statData_file:
                expNumber = expNumber + 1
                lineString = ""
                i=0
                # read a line data and generate list of fields
                while i < len(line):
                    if not (line[i] == " "):
                        lineString = lineString + str(line[i].strip())
                        if i == len(line)-1:
                            lineField.append(lineString.strip())
                    else:
                        lineField.append(lineString.strip())
                        lineString = ""
                    i = i+1
                conNumOutInt = conNumOutInt + int(lineField[2].strip())
                aveDelay = aveDelay + float(lineField[3].strip())
                numOutInt = numOutInt + int(lineField[4].strip())
                intPacLossRate = intPacLossRate + float(lineField[8].strip())
                dataPacLossRate = dataPacLossRate + float(lineField[9].strip())
                pacLossRate = pacLossRate + float(lineField[10].strip())
                lineField = []
            conNumOutInt = conNumOutInt /expNumber
            numOutInt = numOutInt / expNumber
            aveDelay = aveDelay /expNumber
            intPacLossRate = intPacLossRate / expNumber
            dataPacLossRate = dataPacLossRate / expNumber
            pacLossRate = pacLossRate / expNumber
            # Get the number of nodes according to the file name of a statistical data file. 
            graphData = nodeNumber + " " + str(conNumOutInt) + " " + str(aveDelay) + " " + str(numOutInt) + " " \
                        + str(intPacLossRate) + " " + str(dataPacLossRate) + " " + str(pacLossRate)
            graphData_file.write("{0}\n".format(graphData))
            statData_file.close()
        except:
            pass
    graphData_file.close()

# Generate x, y axios data from graphData.dat generated by different routing mechanism.
def genAxiosData(dataFilePath, graphDataDir):
    nodes = []
    conNumOutInt = []
    aveDelay = []
    intPacLossRate = []
    numOutInt = []
    input_file = open("%s/data/%s/graphData.dat" % (dataFilePath,graphDataDir), "r")
    lineField=[]
    for line in input_file:
        lineString = ""
        i=0
        # read a line data and generate list of fields
        while i < len(line):
            if not (line[i] == " "):
                lineString = lineString + str(line[i].strip())
                if i == len(line)-1:
                    lineField.append(lineString.strip())
            else:
                lineField.append(lineString.strip())
                lineString = ""
            i = i+1
        nodes.append(int(lineField[0]))
        conNumOutInt.append(float(lineField[1]))
        aveDelay.append(float(lineField[2]))
        numOutInt.append(float(lineField[3]))
        intPacLossRate.append(float(lineField[4]))
        lineField=[]
    input_file.close()
    return nodes, conNumOutInt, aveDelay, numOutInt, intPacLossRate

# Draw statistical graph
def drawStatGraph(dataFilePath, graphDataDir1, graphDataDir2):
    # setting a style to use
    plt.style.use('fivethirtyeight')
    # create a figure
    fig = plt.figure()
    #fig.savefig('datagraph.pdf')
    #fig.patch.set_facecolor('white') #backgroud color
    # define subplots and their positions in figure
    plt1 = fig.add_subplot(221, axisbg='white')
    plt2 = fig.add_subplot(222, axisbg='white')
    plt3 = fig.add_subplot(223, axisbg='white')
    plt4 = fig.add_subplot(224, axisbg='white')
    # plotting the line 1 points
    plt1.axis([0, 35, 0, 2.5])
    plt2.axis([0, 35, 4, 10])
    plt3.axis([0, 35, 0, 10])
    plt4.axis([0, 35, 0, 150])
    nodes, conNumOutInt, aveDelay, numOutInt, intPacLossRate = genAxiosData(dataFilePath, graphDataDir1)
    plt1.plot(nodes, intPacLossRate, color='blue', linestyle='solid', label = "Opportunity",marker='s', markerfacecolor='blue', markersize=12)
    plt2.plot(nodes, conNumOutInt, color='blue', linestyle='solid', label = "opportunity",marker='s', markerfacecolor='blue', markersize=12)
    plt3.plot(nodes, aveDelay, color='blue', linestyle='solid',label="opportunity", marker='s', markerfacecolor='blue', markersize=12)
    plt4.plot(nodes, numOutInt, color='blue', linestyle='solid',label="opportunity", marker='s', markerfacecolor='blue', markersize=12)

    nodes, conNumOutInt, aveDelay, numOutInt, intPacLossRate = genAxiosData(dataFilePath, graphDataDir2)
    plt1.plot(nodes, intPacLossRate, color='red', linestyle='solid', label = "Bread Crumb",marker='s', markerfacecolor='red', markersize=12)
    plt2.plot(nodes, conNumOutInt, color='red', linestyle='solid', label = "Bread Crumb",marker='s', markerfacecolor='red', markersize=12)
    plt3.plot(nodes, aveDelay, color='red', linestyle='solid',label="Bread Crumb", marker='s', markerfacecolor='red', markersize=12)
    plt4.plot(nodes, numOutInt, color='red', linestyle='solid',label="Bread Crumb", marker='s', markerfacecolor='red', markersize=12)

    plt1.set_title('Interest Packet Loss Rate')
    plt2.set_title('Numbers of Interest Packet')
    plt3.set_title('Average Delay')
    plt4.set_title('The Total Number of Interest Packet')
    #plt1.xlabel('nodes')
    #plt1.ylabel('ISR')
    #plt1.title('Average Delay')
    plt1.legend(loc='upper left')
    plt2.legend(loc='upper left')
    plt3.legend(loc='upper left')
    plt4.legend(loc='upper left')
    plt.show()

if __name__ == '__main__':

    setLogLevel('info')
    dataFilePath = os.path.abspath(os.path.dirname(sys.argv[0]))
    # Delete date file that summaried statistical result.
    graphData_file = "%s/data/oppo/graphData.dat" % dataFilePath
    if os.path.isfile(graphData_file):
        call(["sudo", "rm", graphData_file])
    graphData_file = "%s/data/bread/graphData.dat" % dataFilePath
    if os.path.isfile(graphData_file):
        call(["sudo", "rm", graphData_file])
    # generate data for drawing statistic graph
    drawGraph(dataFilePath, 'oppo')
    drawGraph(dataFilePath, 'bread')
    # draw comparision graph
    drawStatGraph(dataFilePath, "oppo", "bread")

